/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'entertainment' : IDL.Null,
  'tech' : IDL.Null,
  'business' : IDL.Null,
  'sports' : IDL.Null,
  'politics' : IDL.Null,
});
export const Article = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'summary' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Earning = IDL.Record({
  'title' : IDL.Text,
  'coins' : IDL.Nat,
  'articleId' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const LeaderboardEntry = IDL.Record({
  'name' : IDL.Text,
  'totalCoinsEarned' : IDL.Nat,
});
export const Withdrawal = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'ifscCode' : IDL.Text,
  'coins' : IDL.Nat,
  'timestamp' : IDL.Int,
  'accountNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEarningsHistory' : IDL.Func([], [IDL.Vec(Earning)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWallet' : IDL.Func(
      [],
      [
        IDL.Record({
          'balance' : IDL.Nat,
          'totalEarned' : IDL.Nat,
          'readArticles' : IDL.Vec(IDL.Nat),
          'inrValue' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getWithdrawals' : IDL.Func([], [IDL.Vec(Withdrawal)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordArticleRead' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitWithdrawal' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'entertainment' : IDL.Null,
    'tech' : IDL.Null,
    'business' : IDL.Null,
    'sports' : IDL.Null,
    'politics' : IDL.Null,
  });
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'summary' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Earning = IDL.Record({
    'title' : IDL.Text,
    'coins' : IDL.Nat,
    'articleId' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const LeaderboardEntry = IDL.Record({
    'name' : IDL.Text,
    'totalCoinsEarned' : IDL.Nat,
  });
  const Withdrawal = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'ifscCode' : IDL.Text,
    'coins' : IDL.Nat,
    'timestamp' : IDL.Int,
    'accountNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEarningsHistory' : IDL.Func([], [IDL.Vec(Earning)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWallet' : IDL.Func(
        [],
        [
          IDL.Record({
            'balance' : IDL.Nat,
            'totalEarned' : IDL.Nat,
            'readArticles' : IDL.Vec(IDL.Nat),
            'inrValue' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getWithdrawals' : IDL.Func([], [IDL.Vec(Withdrawal)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordArticleRead' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitWithdrawal' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };