/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : bigint,
  'title' : string,
  'duration' : bigint,
  'summary' : string,
  'imageUrl' : string,
  'category' : Category,
}
export type Category = { 'entertainment' : null } |
  { 'tech' : null } |
  { 'business' : null } |
  { 'sports' : null } |
  { 'politics' : null };
export interface Earning {
  'title' : string,
  'coins' : bigint,
  'articleId' : bigint,
  'timestamp' : bigint,
}
export interface LeaderboardEntry {
  'name' : string,
  'totalCoinsEarned' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Withdrawal {
  'id' : bigint,
  'status' : string,
  'ifscCode' : string,
  'coins' : bigint,
  'timestamp' : bigint,
  'accountNumber' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getArticles' : ActorMethod<[], Array<Article>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEarningsHistory' : ActorMethod<[], Array<Earning>>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWallet' : ActorMethod<
    [],
    {
      'balance' : bigint,
      'totalEarned' : bigint,
      'readArticles' : Array<bigint>,
      'inrValue' : number,
    }
  >,
  'getWithdrawals' : ActorMethod<[], Array<Withdrawal>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordArticleRead' : ActorMethod<[bigint], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitWithdrawal' : ActorMethod<[string, string, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];